### ISSUE TITLE
Raw Web Server for publication of resulting html content

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/supplement-template#1]
Need a Web Server to host publication 
* Must have administrative interface that @MaryLJ (authorized few) can use to replicate html ready content (where the html ready content comes from the IG publisher and mechanics and template defined by the IHE-FHIR workgroup)
* Must have ability to support http redirect management where @MaryLJ (authorized few) can define canonical URI that redirect to current publication root, and where historic publications can be available through appropriate version links as archived (similar to current pdf archive mechanics)
* URL root is something like https://fhir.ihe.net or http://ihe.net/fhir
* Where directory structure below this is Profile specific like http://fhir.ihe.net/mhd/index.html
** Might be useful to have domain identifier, but that might also become issue relative to inter-domain linking or where profiles move between domain committee ownership

**Comment by JohnMoehrke** [comment]
We need administrative tool to copy directories full of files on to this storage space (aka FTP). There is NO request for management on a file-by-file basis. We do NOT need editing capability. The directories we are going to copy there are all managed elsewhere and where they are managed assures that they are internally correct. 

The user will not be expected to accidentally browse here, but will be directed on a profile-by-profile basis from the www.ihe.net web site that Mary will continue to manage.

Note that these directories will be massive; here is a sample of the smallest directory: (280 files, 3.5 Meg)
     http://build.fhir.org/ig/IHE/FormatCode/branches/master/index.html  

More typical will be (1000 files, 2 Gig) -- guessing

There will be one directory like this for EVERY IHE profile -- so 200-500 directories in the next few years.(not going to retrofit the current 200 profiles)... Might double or triple that if we keep around old versions of profiles in an archive.

**Comment by JohnMoehrke** [comment]
I have learned from Grahame, that he is no longer recommending S3 bucket. He is not against it, but it is not enough. One not only needs space, domainname support, bandwidth support, and raw administrative access;   such as S3 provides. But one also needs a functionality of a web server to support a very important function, that of managing redirection urls. This is needed because as an Implementation Guide is revised, the previous needs to be left in place as part of an archive. This presents an important lifecycle function. Today this function is managed by Mary with the publication of the PDF onto the IHE web site. The IHE web site might be able to do this function for us, but it is not clear as we have not looked at this functionality yet.

**Comment by tonesoutherland** [comment]
here are some additional proposed requirements - some of which may be covered in previous comments:

- profile files can be organized into containers (e.g., file folders, labels)
- simplicity and ease of access similar to what is available on ftp.ihe.net today
- accessibility by multiple users
- portability to another platform (e.g., download and move somewhere for archive)

**Comment by JohnMoehrke** [comment]
ITI is further needing the above kind of a resource for publication of Final Text technical framework. Nothing new is added by this except space and scope.

**Comment by costateixeira** [comment]
This seems too complicated and I no longer understand where is the requirement for this supplement-template repository. 
Having implemented something similar, I advise looking at this differently.

**Comment by JohnMoehrke** [comment]
> This seems too complicated and I no longer understand where is the requirement for this supplement-template repository.
> Having implemented something similar, I advise looking at this differently.

@costateixeira This issue is not about templating for IG publication, it is about how IHE publishes the results and maintains it as a normative specification. The build machine is only good for committee work, it can't be the publication site.  This workgroup is about IHE publication of FHIR profiles using the IG publisher. That responsibility of the IHE-FHIR workgroup includes publication, not just IG publisher templating.

As to complexity, I see no complexity here. What you might be seeing as complexity is the kind of detail necessary for a business to make a purchase decision for the long-term. To you these details, like ability to upload bulk set of files into a determined URL, may seem prosaic to you, but without them being specified we would not be able to assure what is delivered to us is satisfactory. We know this as the first solution given to us did not work.

We did second pass ask IHE-Services to support this, they wanted to create software and had a very high cost. There is no need for an app to be created. Again, without proper requirements, we were given a solution that did not work.

I have an IG that needs to be published (FormatCode vocabulary) so that it can be pulled into the FHIR core build, as our vocabulary is a part of the FHIR core build. Thus I need this publication solution today. It needs to be published with canonical URI directing to the publication site. It will likely revise on a regular basis, as it would be updated each time a new Content Profile is published by IHE. The template and layout are already approved by ITI, with the expectation that more adjustments will happen as needed.

Feel free to ignore this issue. I can not.

**Comment by costateixeira** [comment]
This shows my point. I do advise to look at it differently

**Comment by JohnMoehrke** [comment]
Learned today that the sub-directory that hosts the FHIR content on must be able to run ASP or PHP scripts. (Grahame has been invited to add more specific requirements)

**Comment by grahamegrieve** [comment]
The redirects use active content on the server side. For IIS, ASP.net and web.config needs to be supported. For Apache/Nginx/Lightspeed, PHP needs to be enabled. 

The requirements are pretty simple:
* needs to run a mainline web server of the types listed above
* server needs to run scripts as authorised above
* server does not db storage, any authorization privileges, user mgmt etc except what is required to allow file upload
* server needs enough storage space to grow (~10GB should do it for a long time)
* need FTP or equivalent access to copy files into place

@costateixeira not sure what the issue is; these are pretty straight-forward hosting requirements, and you need to host

**Comment by JohnMoehrke** [comment]
Chris reports that Chris Harr is setting up lightsail on our amazon bucket.

https://fhir.ihe.net/<path>/<profile> --- NO because more than FHIR will be published here

https://profiles.ihe.net/<domain>/<profile>
https://profiles.ihe.net/papers/<domain>/<paper>
https://profiles.ihe.net/publications/<domain>/<volume 1/2/3/4>
https://profiles.ihe.net/profiles.html -- master index
https://profiles.ihe.net/transactions.xml - redirection given any transaction identifier (e.g. ITI-21) to the canonical location for use. (new flavor of Appendix B https://www.ihe.net/uploadedFiles/Documents/Templates/IHE_TF_GenIntro_AppB_Transactions_Rev1.0_2018-03-09.pdf)

profiles includes document, conformance resources, examples, test plans, etc.

did not choose
https://specs.ihe.net
https://pubs.ihe.net
https://dev.ihe.net
https://techpubs.ihe.net

**Comment by JohnMoehrke** [comment]
in ihe-fhir meeting we agreed we now have the raw web server. Further issues will be new issues.
