### ISSUE TITLE
Overall structure of an IHE IG

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/supplement-template#11]
what content should be in a FHIR IG - what pages, what diagrams, what content structure?

**Comment by JohnMoehrke** [comment]
Note that much of what you seek is already defined in our current supplement template. It is in a WORD document format, but the components you are describing are there. Pulling them out into a diagram will help everyone, not just IG builders.  I suspect that if you could start the diagramming, others will jump in and help adjust and improve it.

Note that we do have to recognize, as our supplement already does, that there are a few different flavors of IG:
* Vocabulary only (e.g. FormatCode IG)
* Content Profile (e.g. a CDA document, or FHIR document, or Workflow object, or Questionaire) (where the transport is a grouping with one of multiple transports)
* Transaction Profile (e.g. the majority)
* Profile of Profiles (e.g. mXDE that simply orchestrates three other profiles and adding a few processing constraints)
* Realm Profile of a Profile (e.g. French use of PIX)  (often referred to as Volume 4)

These different flavors are a strength that IHE has learned from our experience at doing this. HL7 has not yet figured this out.

Not sure if these flavors should be integrated into one diagram, or get represented as independent diagrams with one overall.

**Comment by keithboone** [comment]
See http://build.fhir.org/ig/IHE/ACDC for one proposal for structure.

**Comment by JohnMoehrke** [comment]
see my update to the readme

**Comment by costateixeira** [comment]
The schema you have there seems a replica of the current IHE document.
I may have some alternative suggestions for structuring the
content, looking at a "newer" way of publishing.
BTW, the glossary is missing or not in the right place.

I'll document an alternative in the other IG, hoping we can discuss it soon.

Kind regards

José

**Comment by JohnMoehrke** [comment]
alternatives are welcome, that is how we can move forward.

Yes it is based on the current supplement. This is deeply part of the governance and identity of IHE. If we do everything like HL7, then we are not distinguished from HL7. Note that the "Volume" indicators are not indication of standalone document, like they are today. I included that tag simply as a grouping mechanism. An implementation guide is still a complete unit, like is produced by the IG publisher.

I was expecting that glossary terms were throughout, but I would agree that new terms would be defined in Volume 1. The glossary is recognized as a managed artifact at the IHE level, not at each IG.

**Comment by costateixeira** [comment]
Didn't mean to discuss and challenge the current ideas, just to say that
I'll present an overall alternative that will allow IHE to get ahead.
(I don't understand the part where we'd do everything like HL7..).

Perhaps sending my diagram without a context was not a good idea - I will
explain it with a context, as a new way of doing things. Glossary included.
