### ISSUE TITLE
IHE History template

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/supplement-template#17]
need a history template for IHE.

**Comment by JohnMoehrke** [comment]
I am happy to do the work, but have no idea how.

**Comment by costateixeira** [comment]
this is already done https://github.com/IHE/fhir-ig-history-template

**Comment by JohnMoehrke** [comment]
then... please explain how to use it. because MHD is in public-comment with a red template with the HL7 logos.

**Comment by costateixeira** [comment]
It was in the script, it is now in Confluence

https://confluence.hl7.org/pages/viewpage.action?pageId=104580055
