### ISSUE TITLE
Update with Keith proposal layout

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/supplement-template#2]
Keith has proposed a layout of the text, and a use of some automation build tools

**Comment by JohnMoehrke** [comment]
@kwboone which github repo do you recommend we look at for your proposal? Is it ACDC, SANER, or something else?

**Comment by JohnMoehrke** [comment]
@keithboone will you be able to join us to discuss keith magic vs jose magic?

**Comment by keithboone** [comment]
I am missing the invite for this meeting on my Calendar.

                Keith



Keith Boone, Enterprise Architect
kboone@ainq.com | (617) 640-7007

AUDACIOUS INQUIRY
Bold Solutions for Connected Healthcare®
ainq.com<https://ainq.com/>|Twitter<https://twitter.com/a_inq>|YouTube<https://www.youtube.com/channel/UCF-wA3wcjce8YniZhxy1O4Q>|Facebook<https://www.facebook.com/AudaciousInquiry/>| LinkedIn<https://www.linkedin.com/company/audacious-inquiry-llc>

**Comment by JohnMoehrke** [comment]
see operating mechanisms described here https://github.com/IHE/supplement-template/wiki/IHE-FHIR-workgroup-Operating-Mechanisms

**Comment by keithboone** [comment]
I'd start with ACDC.  SANER has some stuff we might also find useful, but ACDC is strictly an IHE profile.

**Comment by JohnMoehrke** [comment]
I think time has passed this issue by. seems should close this.
