### ISSUE TITLE
Open Closed issues need to be more prominent in an IG for public comment

### ISSUE THREAD

**Issue by lynnfel** [IHE/supplement-template#24]
Especially when publishing an IG for public comment, we need to make the Open/Closed issues more prominent because that often contains the important issues the Tech Committee is seeking feedback on.

Solving this might be as simple as adding a section heading in bold font on the Home page of an IG, with a link to the issues below that.   Attached below is what it looked like when IMR was published for public comment.

<img width="342" alt="Screen Shot 2022-04-14 at 9 11 55 AM" src="https://user-images.githubusercontent.com/47753616/163410157-3ce0e745-80c7-4817-ab42-2bf9ed2e9096.png">
t

**Comment by JohnMoehrke** [comment]
Our template has the open and closed issues link within a pink/orange box... Radiology chose to remove that box. We can't forbid removal of the box by a committee that choses to remove that box.

**Comment by lynnfel** [comment]
didn't know that.  sorry

**Comment by JohnMoehrke** [comment]
Thanks to @lukeaduncan for checking my statement, and finding it false.
