### ISSUE TITLE
are we agreeing to current solution will use FSH? 

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/supplement-template#3]
Is there ability to do phasing? As in use FSH in early development, where that early development is not part of the normative solution? There was some discussion that FSH might be useful to kickstart a IG, but once the structureDefinitions and other elements are created that manual manipulation takes over. Is this the case? If so, then do we have a staging phase where FSH is used?

**Comment by costateixeira** [comment]
I think we should support FSH but that should not be the only option. Yes, Sushi can generate some of the stuff but not all. And sushi is still catching up with the complexity of the IG publication.
Sushi creates the StructureDefs in the output folder. If other structureDefs already exist, Sushi lets them be (which is handy for example when I have manually generated Logical Models and sushi-generated examples.

**Comment by JohnMoehrke** [comment]
I think FSH is a good base for IHE, recognizing that sushi does allow for other input types.
Biggest concern for me is stability of the publication platform, but I don't see the sushi additional module as radically more unstable than the Grahame publication parts.

**Comment by keithboone** [comment]
I would be concerned NOT using FSH at this point.  If I'm the editor and can make the choice, I will use FSH at this point for ANY IG.  It's more than proven it's value.

**Comment by costateixeira** [comment]
I don't see any reason we'd exclude FHIR Shorthand from the editors' tool
belt. I personally use it on a regular basis, along with the other tools.

**Comment by JohnMoehrke** [comment]
To be clear. I don't think IHE will RESTRICT anything. The question here is if our recommendation is to use sushi and FSH. We have limited resources, I don't think we can document and support many methods of publication as the recommendation. So, the question is if sushi and FSH should be our recommendation to new IHE authors, or should we continue to recommend they edit XML? FSH is clearly easier, and it seems it hits 80% of our needs... the only concern I have is stability, which I argue is not worse that the whole IG publication platform... so my vote is yes, focus on sushi and FSH as the recommendation; don't bother documenting non-sushi editing models. which means our recommendation would be based around sushi and not xml conformance resources.

**Comment by JohnMoehrke** [comment]
@jose bring up an important sub-point in an email to me.... FSH is a good recommendation, but the sushi function to author IG content is potentially problematic. That is to say that today sushi tool does do some manipulation of the IG that are beyond the FSH specification, and thus makes it hard to use IG functionality that is not well aligned with the sushi expectation. 

I understand from the sushi team that they agree to backout of this, having sushi focus only on artifact authoring.

**Comment by JohnMoehrke** [comment]
Any objection to us agreeing to recommend IHE Profile authors use FSH format?
Note we will continue to refine the build for ease of use. This is only about recommendation to IHE Profile author. This would not make non-FSH use forbidden.

**Comment by keithboone** [comment]
None from me.  I heartily recommend it.

**Comment by jtdonnelly** [comment]
Although, I have not used it myself, everything I've heard from others that have used it, support its use highly..

**Comment by costateixeira** [comment]
AFAIK nobody has anything against including FSH; I don't see why this is a
discussion topic.

**Comment by JohnMoehrke** [comment]
@costateixeira The reason to make it a decision is to get the group to consider it. The issue was opened in April when FSH was far less stable. Even today FSH is not yet normative, I am not sure it has made it to a STU ballot. So we are taking a risk in using it, vs using StructureDefinition.

**Comment by costateixeira** [comment]
I don't understand "using if [fsh] vs StructureDefinition", or the need for
fsh to be stable - fsh is just a supporting language to edit some of the
content, and it's fine at that.

**Comment by JohnMoehrke** [comment]
This question is a question to IHE as a ANSI standards organization, with governance, that maintains specifications for 20+ years, that needs to support our technical committees from a panel of experts (this ihe-fhir workgroup). I understand that this question seems odd if it is viewed from the perspective of a consultant on timeframe scoped contract.

This question is not one around forbidding an IHE profile author from using FSH. It is a question of if our group here is ready to support IHE profile authors using FSH, and is IHE as a body ready to maintain a FSH file created today for the next 20 years. This is not a one-time-decision, this is a decision that IHE as a body needs to be able to support for the life of the specification written today.

I have concerns that a FSH file created today, where the original editor retires after the IG makes it to Trial Implementation, may be much harder to maintain. This difficulty is based on the instability of FSH vs the instability of StructureDefinition. I have much more confidence that StructureDefinition is stable. HL7 has not resolved the lifespan of the sushi tool, it is a mitre project today.

As I indicated in the definition of this issue (#3), I think we might serve our IHE editors well to recommend FSH, it is much easier to write initial conformance statements. However I think we might best serve our IHE organization by using the FSH only as an initial step, that once the IG goes to Trial Implementation that the StructureDefinitions that were created by sushi be considered the formal specification. It is possible that 2 years later the sushi tool will still convert the FSH to the exact same StructureDefinition reliably, but it might produce slightly different output. It is this instability of sushi, and the output to StructureDefinition that concerns me around the IHE need as an ANSI standards organization.  
The technical committee that needs to do Change Proposal revisions to an IG would be guided. They might succeed with no problem if they edit the old FSH files and run the build, however that might not produce the same StructureDefinition. Thus we might choose to recommend they make those changes to the StructureDefinition, and archive the FSH files as historic authoring artifacts.

I am equally confident that sushi will become stable enough (not that the build tool itself is all that stable today). 

In my original writing of this issue, I proposed that we might recommend a phased approach. I ask the question because I might be the only one that is concerned with the stability and reliability of sushi. Others have indicated they have confidence that sushi is or soon-will-be stable enough. Thus It appears that I am alone in my concern?

**Comment by costateixeira** [comment]
I don't think we should be elevating sushi and fsh to anything normative,
perhaps this is why I cannot understand the open issue.

I'm sorry but I cannot join the call today

**Comment by JohnMoehrke** [comment]
in ihe-fhir meeting. discussion was positive to us recommending and supporting FSH and sushi.
Our template would focus on instructing an IHE Profile (IG) editor to use FSH rather than xml or json conformance resource.
We would be prepared to support these authors.
Ask for tutorial from Mitre, or use existing.

**Comment by costateixeira** [comment]
"our template would focus to use FSH **rather than** xml" ?
- I don't see how this is viable.

**Comment by JohnMoehrke** [comment]
There is some voiced concern that the conclusion is an indication that IHE would forbid the use of xml or json structureDefinition. This is NOT true. The conclusion is focused only on our example template and instructions. We simply decided that we will provide instructions on how to write constraints in FSH, and we will then not include instructions on how to write xml or json.  If an IHE author needs to use, or prefers to use, a StructureDefinition, they are free to use them. However if they have trouble, we might be less capable to help. This should not be a problem as the zulip chat community is there to help.

**Comment by costateixeira** [comment]
This is clearer, although I expect people will need to manually edit
resources anyway( or use other tools) to create some structuredefs, or
codesystems, valuesets, examplescenarios, capabilitystatements,
plandefinitions, namingsystems... hence my support for fsh as simply
another way to enter data. and my focus would be on "what do we need to
produce".
And sushi is still not well integrated with the Publisher ecosystem.
