### ISSUE TITLE
Keith magic diagrammed

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/supplement-template#6]
Jose has done a huge service and visualized the Keith magic xml
https://github.com/IHE/FHIR_IG_content/blob/master/source/option1.md

Which brings up some issues that may or may not be a problem with the model

0) I assume the diagram simply doesn't represent repetitions. For example a Transaction is made up of 1..* message, not just one.  I think this is incorrectly diagrammed in the Transaction box as "message" and "message.result". This should just be message with 1..* repetitions.
1) Actors are not only arranged in responder / initiator relationship. When we get to doing more IHE appropriate IG, that is those that work with 3 or more actors, we will need to be more event driven. Which is the model that IHE is based upon. Each transaction is triggered by 1..* events. 
2) Fundamentally we need to more carefully recognize the Transaction model in IHE. A Transaction is not the same as a Message. A Transaction is made up of 1..* messages.  A Transaction gets some Interoperability task accomplished between 2 or more Actors.  The dominant one is indeed initiator / responder -- serial set of messages: message 1 happens, message 2 is the response upon success, message 3 is the response upon failure;  BUT, it is important to note that the model in IHE is that each message starts with the description of the trigger event for that message. Thus one can have in one Transaction a set of messages that are not connected at all (PAM is a good example where all the messages described within are each defining a variation of patient identity management tasks) 
2.a) included but for clarity - The message then has encoding rules (which align well with StructureDefinition profile). Although it is not always a simple one-for-one.
2.b) included but for clarity -  The message ends with expected actions. This is completely missing in FHIR, and they are now realizing this and trying to figure out how to manage it. Often this expected action is an obvious thing like search your database, or save this data for later... but can be a much more involved workflow based action.
3) Transactions need to identify the Actors that use the transaction, and what role they play. The concept of "role" is not always needed, it is only needed when some IG needed to bring in a different Actor but it will play a role of one of the more primary Actors. (XDS needed this because we needed to group two actors into a new Actor - IntegratedSourceRepository, thus in a Register transaction this Actor plays the role of Registry. )
4) Examples -- The kind of example associated with a Transaction would be an example Message. This would not be an ExampleCase (sp?). If what is being intended by ExampleCase is a use-case for the whole IG, then that would be done at the IG level, not at the transaction level. It is at the IG level that one has access to ALL of the Actors, all the Transactions, all the Content, all the Options. It is at this level that one can write a example scenario that shows the whole purpose of the IG. This should be most of the time linked to the Use Case, but often the use case is too high level for example scenarios..

**Comment by JohnMoehrke** [comment]
5. Actors have the relationship to Transactions in the context of a IG... but Actors also live alone and when living alone can be used by many IG. 
6. Vocabulary -- I presume this is mostly ValueSets, but could also be CodeSystems and ConceptMaps. right? Should we state that?  Do we need to have a distinction in this area for vocabulary specifically pulled into an IG from SNOMED, LOINC, RxNorm, etc? I know we are working on procedures when an IG leverages some of these external sources.
7. Option -- sometimes options are just a set of behaviors,  sometimes they are different constraints in a transaction or content. etc... An Option is always specific to one or more Actors (which I understand is the "has option" relationship, so not clear what the actor element holds). Is the definition diagrammed for Option too focused on transaction?
8. Should we have Glossary diagramed?

**Comment by JohnMoehrke** [comment]
5. Actors have the relationship to Transactions in the context of a IG... but Actors also live alone and when living alone can be used by many IG. 
6. Vocabulary -- I presume this is mostly ValueSets, but could also be CodeSystems and ConceptMaps. right? Should we state that?  Do we need to have a distinction in this area for vocabulary specifically pulled into an IG from SNOMED, LOINC, RxNorm, etc? I know we are working on procedures when an IG leverages some of these external sources.
7. Option -- sometimes options are just a set of behaviors,  sometimes they are different constraints in a transaction or content. etc... An Option is always specific to one or more Actors (which I understand is the "has option" relationship, so not clear what the actor element holds). Is the definition diagrammed for Option too focused on transaction?
8. Should we have Glossary diagramed?

**Comment by costateixeira** [comment]
Just for awareness, I mentioned I would start with documenting what I
understood from Keith's diagrams, and I then I went to document my ideas.

Here is the overview:
https://github.com/IHE/FHIR_IG_content/blob/master/source/be_target.md

Then I will document the attributes and relations between these - I expect
this will answer several questions and bring other questions.

I started an IHE repo but will setup a Belgium IG for these aspects.

Kind regards
Jose

**Comment by JohnMoehrke** [comment]
please don't set up YET ANOTHER repo... just add your stuff to this repo.

John Moehrke 🔥 Architect: Healthcare Informatics Standards -
Interoperability, Privacy, and Security
CyberPrivacy – Enabling authorized communications while respecting Privacy
IHE Co-Chair IT Infrastructure Planning and Technical
HL7 Co-Chair Security WG, FHIR FMG, FHIR facilitator, and FHIR Foundation
founding member
HITRUST Certified CSF Practitioner
Employee of ByLight Professional IT Services -- Contractor to VHA
MyHealtheVet
JohnMoehrke@gmail.com  |  M +1 920-564-2067  |  John.Moehrke@bylight.com
https://www.linkedin.com/in/johnmoehrke   |
https://healthcaresecprivacy.blogspot.com
Courtney's third law: There are no technical solutions to management
problems, but there are management solutions to technical problems.

**Comment by costateixeira** [comment]
This is unrelated and I prefer to follow Ketih's example to setup something
that works and others can see.
We are all experimenting, and I just need a couple benches to experiment on
and to filter the input to the group.

Cheers

Jose

**Comment by JohnMoehrke** [comment]
I also realized that there is a method of documenting in IHE Profiles for three kinds of "grouping". 
1. Mandatory grouping. This actor must always be implemented with this other actor. Together they provide a functionality. 
2. Optional grouping, as in a declared option on an Actor declares that the actor will be grouped with another actor. Together they provide a functionality that independently implemented is not provided.
3. Grouping behavior. There is no mandatory or optional grouping, BUT when these two actors are implemented within a single system, then there is a difference in the way they operate.  The most visible one of these is ATNA Secure Node or Secure Application; as when this is implemented in a system with other IHE defined actors, then the other IHE defined actors transactions will be secured using ATNA secure communications, and when the other IHE defined actor transacts there will be a well-defined audit event logged.
