### ISSUE TITLE
License recommendation

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/supplement-template#7]
When someone creates a GitHub Repo for developing their IG, what is the recommendation from IHE when that Repo is for the purposes of IHE?

I tend to use CC0 most, but am not sure that is right. So would like an authority to define. 

I think I have also heard some argue that better is apache-2.0 or cc-by-4.0

License | License keyword
-- | --
Academic Free License v3.0 | afl-3.0
Apache license 2.0 | apache-2.0
Artistic license 2.0 | artistic-2.0
Boost Software License 1.0 | bsl-1.0
BSD 2-clause "Simplified" license | bsd-2-clause
BSD 3-clause "New" or "Revised" license | bsd-3-clause
BSD 3-clause Clear license | bsd-3-clause-clear
Creative Commons license family | cc
Creative Commons Zero v1.0 Universal | cc0-1.0
Creative Commons Attribution 4.0 | cc-by-4.0
Creative Commons Attribution Share Alike 4.0 | cc-by-sa-4.0
Do What The F*ck You Want To Public License | wtfpl
Educational Community License v2.0 | ecl-2.0
Eclipse Public License 1.0 | epl-1.0
European Union Public License 1.1 | eupl-1.1
GNU Affero General Public License v3.0 | agpl-3.0
GNU General Public License family | gpl
GNU General Public License v2.0 | gpl-2.0
GNU General Public License v3.0 | gpl-3.0
GNU Lesser General Public License family | lgpl
GNU Lesser General Public License v2.1 | lgpl-2.1
GNU Lesser General Public License v3.0 | lgpl-3.0
ISC | isc
LaTeX Project Public License v1.3c | lppl-1.3c
Microsoft Public License | ms-pl
MIT | mit
Mozilla Public License 2.0 | mpl-2.0
Open Software License 3.0 | osl-3.0
PostgreSQL License | postgresql
SIL Open Font License 1.1 | ofl-1.1
University of Illinois/NCSA Open Source License | ncsa
The Unlicense | unlicense
zLib License | zlib

**Comment by JohnMoehrke** [comment]
HL7 gives the following recommendations to IG authors:

LICENSE | A standard file used by Github to indicate what open-source license applies to the contents of the repository. For implementation guides published by HL7 International (including accelerator projects such as Da Vinci that use the HL7 ballot process), this must refer to HL7's FHIR license and the CC0 license.
-- | --


So it seems they have chosen CC0, but it also seems they have guidance on pointing at HL7 license.  It is not clear to me what this looks like. But I do find this license file on the source github repository for their ig author guidance https://github.com/FHIR/ig-guidance/blob/master/LICENSE

> Copyright (c) 2017, HL7
> 
> This document is licensed under the terms of HL7's FHIR license.
> http://hl7.org/fhir/license.html
> 
> Creative Commons "No Rights Reserved" (CC0)

**Comment by keithboone** [comment]
I would prefer CC-BY-4.0, as it is simplest (beyond CC0 which is actually the easiest, but I think we want some recognition). Among the list of licenses that I don't worry to hard about are Apache, BSD, Eclipse, and MIT licenses.  Lesser GNU licenses are OK, but prevent some from being able to use material because of the misunderstandings about the differences between full and lesser GNU licensing.  Full GNU licensing prevents a great deal of commercial use, and shouldn't be considered.

**Comment by costateixeira** [comment]
Agree with Keith on CC (I did not read the difference between CC-BY-4.0 and
CC0, but I don't need to have an opinion there)
Especially agree with not using GNU GPL.

**Comment by JohnMoehrke** [comment]
I think I agree with CC-by-4.0
should we do like HL7 and add an IHE line to the license file?
if we add an IHE line, should CC-by-4.0 be first so as to enable widest automatic processing? or IHE first to be most specific even if less automatic processable

**Comment by ElliotSilver** [comment]
I came across a license that allowed unlimited copying in part or in whole, with no modification, as long as the owner was acknowledged. It seemed reasonable for our uses, and I think is largely the same as CC-by-4.0, although I don't believe the CC-by-4.0 has the "no modification" restriction. I wish I could recall where I came across that license.

**Comment by dididavis** [comment]
I vote for CC-by-4.0 and I do believe we need to add an IHE line to the license file first similar to HL7.  Just my 2 cents worth.

**Comment by JohnMoehrke** [comment]
Any objection to CC-by-4.0?

**Comment by jtdonnelly** [comment]
None from me...   Re an IHE line, does IHE even have a FHIR one?  Or would this be a general IHE one without a FHIR designation?

**Comment by JohnMoehrke** [comment]
> None from me... Re an IHE line, does IHE even have a FHIR one? Or would this be a general IHE one without a FHIR designation?

@jtdonnelly this only comes up because github has a built in license at the github level.  Further this mechanism is automated and computer processable. So it is helpful to the audience if we use one of the standards based licenses.  (standards organizations using standards... :-)

I agree with your statement around the things we publish on the ihe.net domain.

**Comment by ElliotSilver** [comment]
My only issue is that I don't think CC-by-4.0 has a no modification clause. We  don't want people to pass something off as an IHE standard that isn't.

**Comment by JohnMoehrke** [comment]
@ElliotSilver It does allow technical modifications (the shortened graphic seems to indicate a form of modification allowed that is more than the words say). I don' think we are worried about this level of modification, right?

       4. Media and formats; technical modifications allowed. The
          Licensor authorizes You to exercise the Licensed Rights in
          all media and formats whether now known or hereafter created,
          and to make technical modifications necessary to do so. The
          Licensor waives and/or agrees not to assert any right or
          authority to forbid You from making technical modifications
          necessary to exercise the Licensed Rights, including
          technical modifications necessary to circumvent Effective
          Technological Measures. For purposes of this Public License,
          simply making modifications authorized by this Section 2(a)
          (4) never produces Adapted Material.

**Comment by JohnMoehrke** [comment]
Meeting discussion agreed to CC-by-4.0 as the recommendation for github and IG publication.
Note: DCC should be made available. 
Note: sponsors and IHE-International should be notified and they may give us feedback to change.
