### ISSUE TITLE
Process used from committee approval to published works

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/supplement-template#8]
Given the IHE Governance regarding publication of Public Comment, Trial Implementation, Final Text, or white papers; what are the process steps and who is the responsibile actor(s) for each step. 

HL7/FHIR has a written procedure that Grahame is has published, and for which Grahame is the actor for all of these tasks. Presumably when IHE workgroup approves a publication, we will need to do similar steps. 

See https://confluence.hl7.org/display/FHIR/Process+for+Publishing+a+FHIR+IG

**Comment by JohnMoehrke** [comment]
discussion with Grahame and Jose on the process
https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/IG.20releases/near/196823326

**Comment by keithboone** [comment]
It's documented, but not without challenges, and there's a LOT of manual processing involved as I understand it today.  Yes, we will need a process, but hopefully, it is lighter-weight.

**Comment by JohnMoehrke** [comment]
@costateixeira has a simplified version of these instructions https://github.com/costateixeira/ig-publication

**Comment by JohnMoehrke** [comment]
I will execute Jose's process, given my FormatCode, and Chris's new web site.

**Comment by JohnMoehrke** [comment]
> @costateixeira has a simplified version of these instructions https://github.com/costateixeira/ig-publication

This procedure is one that an editor would use to create an IG. 

The issue #8 is about the process used after an IG has been drafted and approved by the IHE domain. This process needs to include any fixup needed, confirmation of proper copyright etc. So I am going back at looking at Grahame's procedure which is more on topic for issue #8
    https://confluence.hl7.org/display/FHIR/Process+for+Publishing+a+FHIR+IG
